Loaded module: python3/3.6.2
Loaded module: cuda/9.2
Loaded module: cudnn/v7.4.2.24-prod-cuda-9.2
Error: [Errno 1] Operation not permitted: '/work3/s164440/shared/IllumiGANResearch/env/bin/activate.fish'
Traceback (most recent call last):
  File "train.py", line 79, in <module>
    model.optimize_parameters()
  File "/work3/s164440/shared/IllumiGANResearch/models/illumigan_model.py", line 254, in optimize_parameters
    self.d_backward()
  File "/work3/s164440/shared/IllumiGANResearch/models/illumigan_model.py", line 219, in d_backward
    real_loss = self.GAN_loss.compute(real_prediction, 1)
  File "/work3/s164440/shared/IllumiGANResearch/models/nets.py", line 208, in compute
    t_target = self.create_target(size, target)
  File "/work3/s164440/shared/IllumiGANResearch/models/nets.py", line 201, in create_target
    t_target.expand(size)
AttributeError: 'int' object has no attribute 'expand'
